// <auto-generated />
using ImageHUB.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImageHUB.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191107120753_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("ImageHUB.Repositories.Post", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("ProfileID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("ProfileID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ImageHUB.Repositories.Profile", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("Email");

                    b.Property<string>("ProfileID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("ProfileID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ImageHUB.Repositories.Post", b =>
                {
                    b.HasOne("ImageHUB.Repositories.Profile")
                        .WithMany("Posts")
                        .HasForeignKey("ProfileID");
                });

            modelBuilder.Entity("ImageHUB.Repositories.Profile", b =>
                {
                    b.HasOne("ImageHUB.Repositories.Profile")
                        .WithMany("Friends")
                        .HasForeignKey("ProfileID");
                });
#pragma warning restore 612, 618
        }
    }
}
